steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "--tag=gcr.io/$PROJECT_ID/algo-book:latest"
          - "--file=./docker/production/Dockerfile"
          - "."
