version: "3"
services:
    api:
        build:
            context: .
            dockerfile: ./docker/server/dev.dockerfile
        volumes:
            - /app/node_modules
            # - ./ :/app
    client:
        build:
            context: .
            dockerfile: ./docker/client/dev.dockerfile
        volumes:
            - /app/node_modules
            # - ./ :/app
        stdin_open: true
